services:
  xx_unleash_proxy:
    container_name: xx-unleash-proxy
    build: .
    restart: always
    working_dir: /usr/src/app
    command: yarn start
    environment:
      UNLEASH_API_URL:
      UNLEASH_API_TOKEN: 
      UNLEASH_API_SECRET: 
    ports:
      - 4243:4243